version: "3.11"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file: .env
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: /dist/Dockerfile
    restart: unless-stopped
    env_file: .env

    depends_on:
      - redis
      - postgres

    # You can remove this fields if you don't use webhooks.
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"

volumes:
  redis-data:
  postgres-data:
