services:
  redis:
    image: redis:7-alpine
    restart: always
    env_file: .env
    command: --port ${REDIS_PORT}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - bot_network

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bot_network

  bot:
    build: .
    restart: always
    env_file: .env

    depends_on:
      - redis
      - postgres

    # You can remove this fields if you don't use webhooks.
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"

    networks:
      - bot_network

volumes:
  redis-data:
  postgres-data:


networks:
  bot_network:
