[tool.poetry]
name = "aiogram_template"
version = "1.0.0"
description = "basic aiogram template"
authors = ["Angel <145038102+KurosawaAngel@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "aiogram_template", from = "src"}]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"
alembic = "^1.13.0"
pydantic-settings = "^2.5.2"
aiogram-dialog = "2.2.0"
aiogram = "^3.13.0"
dishka = "^1.3.0"
aiogram-i18n = { git = "https://github.com/aiogram/i18n", rev = "cd35798"}
redis = "^5.0.8"
jinja2 = "^3.1.4"


[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
ruff = "^0.6.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["src"]

[tool.ruff.lint.isort]
no-lines-before = ["local-folder"]
