[tool.poetry]
name = "aiogram_template"
version = "1.0.0"
description = "basic aiogram template"
authors = ["KuroAngel <145038102+KuroKoka551@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "aiogram_template", from = "src"}]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.30"
asyncpg = "^0.29.0"
alembic = "^1.13.1"
pydantic-settings = "^2.3.4"
aiogram-dialog = "^2.1.0"
aiogram = "^3.8.0"
dishka = "^1.2.0"
aiogram-i18n = "^1.4"
fluent = { git = "https://github.com/RootShinobi/python-fluent-breaking-standards", rev = "a71c09b"}
redis = "^5.0.4"


[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
ruff = "^0.4.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["src"]

[tool.ruff.lint.isort]
no-lines-before = ["local-folder"]